import Link from "next/link";
import { Ship, FileText } from "lucide-react";
import { getYachtContext } from "@/lib/data/current-yacht";
import { getCurrentUser } from "@/lib/data/current-user";
import { getReportArchive } from "@/lib/data/reports";
import { GenerateReportDialog } from "@/components/reports/generate-report-dialog";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export default async function ReportsPage() {
  const user = await getCurrentUser();
  const { yacht } = await getYachtContext();
  const canGenerate = user?.role === "admin" || user?.role === "technical";

  if (!yacht) {
    return (
      <div className="p-6 max-w-4xl mx-auto">
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center justify-center py-16 text-center gap-3">
            <Ship className="h-10 w-10 text-muted-foreground" />
            <p className="font-medium">No yacht yet</p>
            <Button asChild size="sm">
              <Link href="/yacht-profile">Create Yacht Profile</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const reports = await getReportArchive(yacht.id);

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Bi-weekly environmental monitoring reports for {yacht.name}. Once generated, a report is immutable.
          </p>
        </div>
        {canGenerate && <GenerateReportDialog yachtId={yacht.id} />}
      </div>

      {reports.length === 0 ? (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center justify-center py-16 text-center gap-3">
            <FileText className="h-10 w-10 text-muted-foreground" />
            <div>
              <p className="font-medium">No reports yet</p>
              <p className="text-sm text-muted-foreground max-w-sm">
                {canGenerate
                  ? "Generate your first report to create a shareable, branded PDF for the Captain."
                  : "Ask an admin or technical user to generate the first report."}
              </p>
            </div>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="pt-6">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Period</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Overall Score</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead />
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((r) => (
                  <TableRow key={r.id}>
                    <TableCell className="font-medium">
                      {new Date(r.period_start).toLocaleDateString("en-GB", { day: "2-digit", month: "short" })} –{" "}
                      {new Date(r.period_end).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}
                    </TableCell>
                    <TableCell>
                      <Badge variant={r.status === "final" ? "default" : "secondary"}>{r.status}</Badge>
                    </TableCell>
                    <TableCell>{r.overall_score ?? "—"}</TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {r.app_users?.full_name ?? r.app_users?.email ?? "—"}
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground whitespace-nowrap">
                      {new Date(r.created_at).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}
                    </TableCell>
                    <TableCell>
                      <Button asChild size="sm" variant="ghost">
                        <Link href={`/reports/${r.id}`}>View</Link>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
